// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  describe('Service: cmsSessionService', function() {
    var cmsSessionService;
    beforeEach(module('angularCmsApp'));
    cmsSessionService = {};
    beforeEach(inject(function(_cmsSessionService_) {
      return cmsSessionService = _cmsSessionService_;
    }));
    return it('should do something', function() {
      return expect(!!cmsSessionService).toBe(true);
    });
  });

}).call(this);

/*
//@ sourceMappingURL=cmsSessionService.map
*/
