// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  describe('Directive: cmsFormGroup', function() {
    var scope;
    beforeEach(module('angularCmsApp'));
    scope = {};
    beforeEach(inject(function($controller, $rootScope) {
      return scope = $rootScope.$new();
    }));
    return xit('should make hidden element visible', inject(function($compile) {
      var element;
      element = angular.element('<cms-form-group></cms-form-group>');
      element = $compile(element)(scope);
      return expect(element.html()).toBe('<div class="form-group ng-scope ng-isolate-scope">\n  <label class="control-label col-sm-3 col-xs-3 ng-binding">{{label}}:</label>\n  <div class="controls col-sm-9 col-xs-9" ng-transclude=""></div>\n</div>');
    }));
  });

}).call(this);

/*
//@ sourceMappingURL=cmsFormGroup.map
*/
