// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  describe('Directive: cmsPanel', function() {
    var scope;
    beforeEach(module('angularCmsApp'));
    scope = {
      title: 'Test'
    };
    return beforeEach(inject(function($controller, $rootScope) {
      return scope = $rootScope.$new();
    }));
  });

}).call(this);

/*
//@ sourceMappingURL=cmsPanel.map
*/
