// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  describe('Controller: LoginCtrl', function() {
    var LoginCtrl, scope;
    beforeEach(module('angularCmsApp'));
    LoginCtrl = {};
    scope = {};
    beforeEach(inject(function($controller, $rootScope) {
      scope = $rootScope.$new();
      return LoginCtrl = $controller('LoginCtrl', {
        $scope: scope
      });
    }));
    return it('should attach a list of awesomeThings to the scope', function() {});
  });

}).call(this);

/*
//@ sourceMappingURL=login.map
*/
